### ISSUE TITLE
biotransformer test failing on UMSA

### ISSUE THREAD

**Issue by martenson** [RECETOX/galaxytools#225]
this seems to be related to issue described here https://github.com/RECETOX/galaxytools/pull/12#issuecomment-698943700

reported by @ElliottJP 

traceback when running on UMSA with test data:

```
Error loading JNI InChI native code.
You may need to compile the native code for your platform.
See http://jni-inchi.sourceforge.net for instructions.

Exception in thread "main" org.openscience.cdk.exception.CDKException: Unable to load native code; net.sf.jnati.NativeCodeException: Error creating directory: ?/.jnati/repo/jniinchi/1.03_1/LINUX-AMD64
	at org.openscience.cdk.inchi.InChIGeneratorFactory.<init>(InChIGeneratorFactory.java:87)
	at org.openscience.cdk.inchi.InChIGeneratorFactory.getInstance(InChIGeneratorFactory.java:102)
	at biotransformer.btransformers.Biotransformer.<init>(Biotransformer.java:130)
	at biotransformer.btransformers.ECBasedBTransformer.<init>(ECBasedBTransformer.java:56)
	at biotransformer.utils.HumanSuperBioTransformer.<init>(HumanSuperBioTransformer.java:47)
	at executable.BiotransformerExecutable.main(BiotransformerExecutable.java:997)
Caused by: net.sf.jniinchi.LoadNativeLibraryException: net.sf.jnati.NativeCodeException: Error creating directory: ?/.jnati/repo/jniinchi/1.03_1/LINUX-AMD64
	at net.sf.jniinchi.JniInchiWrapper.loadLibrary(JniInchiWrapper.java:98)
	at org.openscience.cdk.inchi.InChIGeneratorFactory.<init>(InChIGeneratorFactory.java:85)
	... 5 more
Caused by: net.sf.jnati.NativeCodeException: Error creating directory: ?/.jnati/repo/jniinchi/1.03_1/LINUX-AMD64
	at net.sf.jnati.deploy.repository.LocalRepository.createArtefact(LocalRepository.java:91)
	at net.sf.jnati.deploy.NativeArtefactLocator.deployArtefactToLocalRepository(NativeArtefactLocator.java:127)
	at net.sf.jnati.deploy.NativeArtefactLocator.getArtefact(NativeArtefactLocator.java:71)
	at net.sf.jnati.deploy.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:47)
	at net.sf.jnati.deploy.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:41)
	at net.sf.jnati.deploy.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:37)
	at net.sf.jniinchi.JniInchiWrapper.loadLibrary(JniInchiWrapper.java:84)
	... 6 more
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 2889, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 97, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1675, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1683, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'InChI'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/volume/shared/galaxy/var/shed_tools/testtoolshed.g2.bx.psu.edu/repos/recetox/biotransformer/6080aee7c4f6/biotransformer/wrapper_biotransformer.py", line 75, in <module>
    out_df1.insert(1, "SMILES target", InchiToSmiles(out_df1))
  File "/mnt/volume/shared/galaxy/var/shed_tools/testtoolshed.g2.bx.psu.edu/repos/recetox/biotransformer/6080aee7c4f6/biotransformer/wrapper_biotransformer.py", line 14, in InchiToSmiles
    for item in df['InChI']:
  File "/usr/local/lib/python3.7/site-packages/pandas/core/frame.py", line 2902, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/usr/local/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 2891, in get_loc
    raise KeyError(key) from err
KeyError: 'InChI'
```

**Comment by hechth** [comment]
This bug is actually related to a change in the biotransformer output, which now apparently no longer contains the `InChI` field - the wrapper has a conversion function to go from InChI to SMILES which is now failing as the source data is not found.

**Comment by martenson** [comment]
Last version change we had was over a year ago. Did it not work since? https://anaconda.org/bioconda/biotransformer/files

**Comment by hechth** [comment]
Probably

**Comment by xtrojak** [comment]
To reproduce the error locally, use `--docker` option when running `planemo`:

```planemo serve --docker```

This will download and run `biotransformer` in a `biocontainer` available [here](https://biocontainers.pro/tools/mulled-v2-d925e0797b0e0fe63ac64483a8abb44d22142ec2) (although sometimes it is built again instead of downloaded, we are not sure why - it might be safer to download it first). Executing the `biotransformer` will result n the error message from above.

---

However, when executing our `biotransformer` wrapper directly using the `biocontainer`, i.e.

```docker run -v <mount a volume> quay.io/biocontainers/mulled-v2-d925e0797b0e0fe63ac64483a8abb44d22142ec2:ab2d9a7f2c9b04bf16025fc6b5104c2b74c9a594-0 <command>```

where `command` represents the wrapper with all arguments, it produces a successful tool run.

**Comment by xtrojak** [comment]
The docker image is run with parameter `--user 1000:1000` meaning the user with `UID 1000` (usually the first user/group ID that is created when installing) is used instead of the default `root`. However, in the above mentioned contained, there is no such user. Adding a user should solve the issue (maybe with `sudo` rights, needs to be confirmed).

**Comment by martenson** [comment]
I changed the destination biotransformer jobs are sent to on umsa, now they are run with 
```
      <param id="docker_set_user">root</param>
```
and the jobs seem to be finishing fine.

I think a important line in the trace that I overlooked before is

```
Caused by: net.sf.jniinchi.LoadNativeLibraryException: net.sf.jnati.NativeCodeException: Error creating directory: ?/.jnati/repo/jniinchi/1.03_1/LINUX-AMD64
```

Which indicated permissions issues.

**Comment by martenson** [comment]
@xtrojak the param translates to `--user root` in the cli
