### ISSUE TITLE
matchms scores formatter numpy import issues

### ISSUE THREAD

**Issue by hechth** [RECETOX/galaxytools#429]
Link to history: https://umsa.cerit-sc.cz/u/hechth/h/hbm-aplcms-qcs-lc-pos-ramclustr

Seems like some internal issues - maybe the bioconda recipe needs some pins and some newer version of numpy causes problems? Probably applying the same pins as in the poetry file of matchms in the bioconda recipe would make sense.

```
OpenBLAS blas_thread_init: pthread_create failed for thread 1 of 8: Operation not permitted
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 2 of 8: Operation not permitted
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 3 of 8: Operation not permitted
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 4 of 8: Operation not permitted
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 5 of 8: Operation not permitted
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 6 of 8: Operation not permitted
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 7 of 8: Operation not permitted
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
Traceback (most recent call last):
  File "/mnt/volume/shared/galaxy/var/shed_tools/toolshed.g2.bx.psu.edu/repos/recetox/matchms_formatter/1e58bf51a0e5/matchms_formatter/formatter.py", line 2, in <module>
    from matchms.importing import scores_from_json
  File "/usr/local/lib/python3.9/site-packages/matchms/__init__.py", line 1, in <module>
    from matchms.filtering.SpectrumProcessor import SpectrumProcessor
  File "/usr/local/lib/python3.9/site-packages/matchms/filtering/__init__.py", line 75, in <module>
    from .default_filters import default_filters
  File "/usr/local/lib/python3.9/site-packages/matchms/filtering/default_filters.py", line 1, in <module>
    from matchms.typing import SpectrumType
  File "/usr/local/lib/python3.9/site-packages/matchms/typing.py", line 2, in <module>
    import numpy as np
  File "/usr/local/lib/python3.9/site-packages/numpy/__init__.py", line 141, in <module>
    from . import core
  File "/usr/local/lib/python3.9/site-packages/numpy/core/__init__.py", line 23, in <module>
    from . import multiarray
  File "/usr/local/lib/python3.9/site-packages/numpy/core/multiarray.py", line 10, in <module>
    from . import overrides
  File "/usr/local/lib/python3.9/site-packages/numpy/core/overrides.py", line 6, in <module>
    from numpy.core._multiarray_umath import (
KeyboardInterrupt
```

**Comment by hechth** [comment]
@zargham-ahmad I think this is solved?

**Comment by hechth** [comment]
this still persists in version 0.24.0 of the matchms galaxy tools

**Comment by hechth** [comment]
Our assumption is that this is somehow related to pandas, numpy or scipy, but we have no absolute idea.
