### ISSUE TITLE
matchms_formatter only works when 'compound_name' is present

### ISSUE THREAD

**Issue by chufz** [RECETOX/galaxytools#444]
Currently, the formatter only works when compound_name is given. However, sometimes spectral similarity is calculated without known compounds, leading to the error message: 

``` Traceback (most recent call last):
  File "/gpfs1/data/galaxy_server/galaxy/shed_tools/toolshed.g2.bx.psu.edu/repos/recetox/matchms_formatter/37da26e798f2/matchms_formatter/formatter.py", line 51, in <module>
    cli()
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1646, in invoke
    super().invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/gpfs1/data/galaxy_server/galaxy/shed_tools/toolshed.g2.bx.psu.edu/repos/recetox/matchms_formatter/37da26e798f2/matchms_formatter/formatter.py", line 45, in cli
    result = load_data(scores_filename)
  File "/gpfs1/data/galaxy_server/galaxy/shed_tools/toolshed.g2.bx.psu.edu/repos/recetox/matchms_formatter/37da26e798f2/matchms_formatter/formatter.py", line 36, in load_data
    scores = scores_to_dataframe(scores)
  File "/gpfs1/data/galaxy_server/galaxy/shed_tools/toolshed.g2.bx.psu.edu/repos/recetox/matchms_formatter/37da26e798f2/matchms_formatter/formatter.py", line 19, in scores_to_dataframe
    data.append([scores.queries[col].metadata['compound_name'], scores.references[row].metadata['compound_name'], *scores.scores.data[i]])
KeyError: 'compound_name' ```

**Comment by hechth** [comment]
@chufz have you tried running matchms convert or filter on your inputs? that might help

**Comment by chufz** [comment]
Yes i converted with matchms convert to the msp in matchms format in advance

**Comment by hechth** [comment]
Okay - we can add an option to choose a different column

**Comment by bgruening** [comment]
`data_column` might be useful here: https://docs.galaxyproject.org/en/latest/dev/schema.html#id33

**Comment by hechth** [comment]
@zargham-ahmad is this still the case? Didn't we include a key in the latest version?

**Comment by zargham-ahmad** [comment]
@hechth yes, this can be closed we added an optional key parameter in the latest version
