### ISSUE TITLE
matchms networking Identifier key is not an optional variable

### ISSUE THREAD

**Issue by chufz** [RECETOX/galaxytools#445]
An error occurs when matchms networking is used without any entry for the Identifier key. However, it is marked as optional in the GUI.

Additionally, the user needs to know that what metadata might be in the metadata of the mgf /msp with capital letters will be transformed to a variable name with lower cases in the json file with the similarity matrix.

Following error occurs: 
``` Traceback (most recent call last):
  File "/gpfs1/data/galaxy_server/galaxy/shed_tools/toolshed.g2.bx.psu.edu/repos/recetox/matchms_networking/3289420aaaca/matchms_networking/matchms_networking_wrapper.py", line 41, in <module>
    main(argv=sys.argv[1:])
  File "/gpfs1/data/galaxy_server/galaxy/shed_tools/toolshed.g2.bx.psu.edu/repos/recetox/matchms_networking/3289420aaaca/matchms_networking/matchms_networking_wrapper.py", line 34, in main
    network.create_network(scores, score_name)
  File "/usr/local/lib/python3.11/site-packages/matchms/networking/SimilarityNetwork.py", line 116, in create_network
    msnet.add_nodes_from(unique_ids)
  File "/usr/local/lib/python3.11/site-packages/networkx/classes/graph.py", line 635, in add_nodes_from
    raise ValueError("None cannot be a node")
ValueError: None cannot be a node ```

**Comment by hechth** [comment]
@chufz seems like this is already implemented - can you double check?
