### ISSUE TITLE
Error running Remove coordination complexes tool

### ISSUE THREAD

**Issue by wverastegui** [RECETOX/galaxytools#450]
Running on csv input format gives:
Unable to find image 'quay.io/biocontainers/mulled-v2-56a9cd89a7bcfbe0bfc3211cebf267f621a9a328:bf898d883411de20ff5ba72fd6e7931180123cd8-0' locally
bf898d883411de20ff5ba72fd6e7931180123cd8-0: Pulling from biocontainers/mulled-v2-56a9cd89a7bcfbe0bfc3211cebf267f621a9a328
fa7e54f17dc0: Already exists
4ca545ee6d5d: Already exists
2c4bff57e247: Pulling fs layer
2c4bff57e247: Download complete
2c4bff57e247: Pull complete
Digest: sha256:68c7206a1b881087f5153be01c607a074641ce9288c19762cd4b9985a4d82aee
Status: Downloaded newer image for quay.io/biocontainers/mulled-v2-56a9cd89a7bcfbe0bfc3211cebf267f621a9a328:bf898d883411de20ff5ba72fd6e7931180123cd8-0
OpenBLAS blas_thread_init: pthread_create failed for thread 1 of 8: Operation not permitted
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 2 of 8: Operation not permitted
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 3 of 8: Operation not permitted
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 4 of 8: Operation not permitted
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 5 of 8: Operation not permitted
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 6 of 8: Operation not permitted
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 7 of 8: Operation not permitted
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
Traceback (most recent call last):
  File "/mnt/volume/shared/galaxy/var/shed_tools/toolshed.g2.bx.psu.edu/repos/recetox/rem_complex/a0e07a0bc047/rem_complex/rem_complex.py", line 3, in <module>
    import pandas as pd
  File "/usr/local/lib/python3.11/site-packages/pandas/__init__.py", line 16, in <module>
    raise ImportError(
ImportError: Unable to import required dependencies:
numpy: Error importing numpy: you should not try to import numpy from
        its source directory; please exit the numpy source tree, and relaunch
        your python interpreter from there.

**Comment by wverastegui** [comment]
running on inchi input format gives:
OpenBLAS blas_thread_init: pthread_create failed for thread 1 of 8: Operation not permitted
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 2 of 8: Operation not permitted
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 3 of 8: Operation not permitted
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 4 of 8: Operation not permitted
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 5 of 8: Operation not permitted
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 6 of 8: Operation not permitted
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 7 of 8: Operation not permitted
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
Traceback (most recent call last):
  File "/mnt/volume/shared/galaxy/var/shed_tools/toolshed.g2.bx.psu.edu/repos/recetox/rem_complex/a0e07a0bc047/rem_complex/rem_complex.py", line 3, in <module>
    import pandas as pd
  File "/usr/local/lib/python3.11/site-packages/pandas/__init__.py", line 16, in <module>
    raise ImportError(
ImportError: Unable to import required dependencies:
numpy: Error importing numpy: you should not try to import numpy from
        its source directory; please exit the numpy source tree, and relaunch
        your python interpreter from there.
