### ISSUE TITLE
advanced xmsannotator issues 

### ISSUE THREAD

**Issue by martenson** [RECETOX/galaxytools#90]
Beware that I do not know what are the correct files to test with, so I am testing on surely invalid files. Nevertheless there seems to be an issue with running the advanced version of the annotator. 

This is the Galaxy traceback when trying to execute the tool:
```
Traceback (most recent call last):
  File "/mnt/volume/shared/galaxy/server/lib/galaxy/tools/__init__.py", line 1657, in handle_single_execution
    flush_job=flush_job,
  File "/mnt/volume/shared/galaxy/server/lib/galaxy/tools/__init__.py", line 1745, in execute
    return self.tool_action.execute(self, trans, incoming=incoming, set_output_hid=set_output_hid, history=history, **kwargs)
  File "/mnt/volume/shared/galaxy/server/lib/galaxy/tools/actions/__init__.py", line 311, in execute
    history, inp_data, inp_dataset_collections, preserved_tags, all_permissions = self._collect_inputs(tool, trans, incoming, history, current_user_roles, collection_info)
  File "/mnt/volume/shared/galaxy/server/lib/galaxy/tools/actions/__init__.py", line 263, in _collect_inputs
    inp_data, all_permissions = self._collect_input_datasets(tool, incoming, trans, history=history, current_user_roles=current_user_roles, collection_info=collection_info)
  File "/mnt/volume/shared/galaxy/server/lib/galaxy/tools/actions/__init__.py", line 209, in _collect_input_datasets
    tool.visit_inputs(param_values, visitor)
  File "/mnt/volume/shared/galaxy/server/lib/galaxy/tools/__init__.py", line 1532, in visit_inputs
    visit_input_values(self.inputs, values, callback)
  File "/mnt/volume/shared/galaxy/server/lib/galaxy/tools/parameters/__init__.py", line 168, in visit_input_values
    visit_input_values(input.inputs, values, callback, new_name_prefix, label_prefix, parent_prefix=name_prefix, **payload)
  File "/mnt/volume/shared/galaxy/server/lib/galaxy/tools/parameters/__init__.py", line 170, in visit_input_values
    callback_helper(input, input_values, name_prefix, label_prefix, parent_prefix=parent_prefix, context=context)
  File "/mnt/volume/shared/galaxy/server/lib/galaxy/tools/parameters/__init__.py", line 131, in callback_helper
    new_value = callback(**args)
  File "/mnt/volume/shared/galaxy/server/lib/galaxy/tools/actions/__init__.py", line 159, in visitor
    target_dict[conversion_name] = conversion_data.id  # a more robust way to determine JSONable value is desired
AttributeError: 'NoneType' object has no attribute 'id'
```

These lines are suspicious because they are inconsistent, but they do not seem to be the cause.
https://github.com/RECETOX/galaxytools/blob/master/tools/xmsannotator/xmsannotator_advanced.xml#L33-L36

Removing the `<conversion>` steps from the tool allows me to execute it. The issue could be with the application of conversion on the optional steps.

Further research with actual valid inputs is required. From what I understand in the code the conversions are not essential, as long as we supply csv as inputs so maybe we can just drop them.

cc @xtracko  @hechth

**Comment by xtracko** [comment]
Ok. Dropping the conversion then
